### PR TITLE
Refactor type definitions

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**
Issue(s): 
https://github.com/blackbaud/skyux-docs-tools/issues/133
https://github.com/blackbaud/skyux-docs-tools/issues/123
https://github.com/blackbaud/skyux-docs-tools/issues/114
https://github.com/blackbaud/skyux-docs-tools/issues/28

**Overview of changes:**
- `SkyDocsTypeDefinitionsService`: Handles all type definitions that have been converted from the third-party documentation generator.
- `SkyDocsTypeDefinitionsFormatService`: Formats type definitions into HTML-compatible strings.
- `SkyDocsTypeDocAdapterService`: Converts TypeDoc types into SKY UX docs-tools types, to be supplied to the various definitions components.

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-docs-tools?_sp.spa=pr-refactor-type-defs](https://host.nxt.blackbaud.com/skyux-docs-tools?_sp.spa=pr-refactor-type-defs)

**Comment by blackbaud-ado** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-docs-tools?_sp.spa=pr-refactor-type-defs](https://host.nxt.blackbaud.com/skyux-docs-tools?_sp.spa=pr-refactor-type-defs)

**Comment by blackbaud-ado** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-docs-tools?_sp.spa=pr-refactor-type-defs](https://host.nxt.blackbaud.com/skyux-docs-tools?_sp.spa=pr-refactor-type-defs)

**Review by Blackbaud-AlexKingman — APPROVED** [review]
Well done 👏 👏 👏

**Comment by blackbaud-ado** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-docs-tools?_sp.spa=pr-refactor-type-defs](https://host.nxt.blackbaud.com/skyux-docs-tools?_sp.spa=pr-refactor-type-defs)

**Pull request merged**
